<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Poll', 'doctrine');

/**
 * BasePoll
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $layout_id
 * @property enum $type
 * @property integer $self_answers
 * @property timestamp $created_at
 * @property Layout $Layout
 * @property Doctrine_Collection $PollComment
 * @property Doctrine_Collection $Questions
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method integer             getLayoutId()     Returns the current record's "layout_id" value
 * @method enum                getType()         Returns the current record's "type" value
 * @method integer             getSelfAnswers()  Returns the current record's "self_answers" value
 * @method timestamp           getCreatedAt()    Returns the current record's "created_at" value
 * @method Layout              getLayout()       Returns the current record's "Layout" value
 * @method Doctrine_Collection getPollComment()  Returns the current record's "PollComment" collection
 * @method Doctrine_Collection getQuestions()    Returns the current record's "Questions" collection
 * @method Poll                setId()           Sets the current record's "id" value
 * @method Poll                setName()         Sets the current record's "name" value
 * @method Poll                setLayoutId()     Sets the current record's "layout_id" value
 * @method Poll                setType()         Sets the current record's "type" value
 * @method Poll                setSelfAnswers()  Sets the current record's "self_answers" value
 * @method Poll                setCreatedAt()    Sets the current record's "created_at" value
 * @method Poll                setLayout()       Sets the current record's "Layout" value
 * @method Poll                setPollComment()  Sets the current record's "PollComment" collection
 * @method Poll                setQuestions()    Sets the current record's "Questions" collection
 * 
 * @package    ibum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePoll extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('poll');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('layout_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('type', 'enum', 6, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'check',
              1 => 'radio',
              2 => 'points',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('self_answers', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Layout', array(
             'local' => 'layout_id',
             'foreign' => 'id'));

        $this->hasMany('PollComment', array(
             'local' => 'id',
             'foreign' => 'poll_id'));

        $this->hasMany('Questions', array(
             'local' => 'id',
             'foreign' => 'poll_id'));
    }
}