<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('QuestionsResults', 'doctrine');

/**
 * BaseQuestionsResults
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $result
 * @property string $icon
 * @property string $title
 * @property string $advice
 * 
 * @method integer          getId()     Returns the current record's "id" value
 * @method string           getResult() Returns the current record's "result" value
 * @method string           getIcon()   Returns the current record's "icon" value
 * @method string           getTitle()  Returns the current record's "title" value
 * @method string           getAdvice() Returns the current record's "advice" value
 * @method QuestionsResults setId()     Sets the current record's "id" value
 * @method QuestionsResults setResult() Sets the current record's "result" value
 * @method QuestionsResults setIcon()   Sets the current record's "icon" value
 * @method QuestionsResults setTitle()  Sets the current record's "title" value
 * @method QuestionsResults setAdvice() Sets the current record's "advice" value
 * 
 * @package    ibum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuestionsResults extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('questions_results');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('result', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('icon', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('advice', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}