<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Layout', 'doctrine');

/**
 * BaseLayout
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $head_image
 * @property string $background_image
 * @property string $bottom_image
 * @property Doctrine_Collection $Poll
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getHeadImage()        Returns the current record's "head_image" value
 * @method string              getBackgroundImage()  Returns the current record's "background_image" value
 * @method string              getBottomImage()      Returns the current record's "bottom_image" value
 * @method Doctrine_Collection getPoll()             Returns the current record's "Poll" collection
 * @method Layout              setId()               Sets the current record's "id" value
 * @method Layout              setHeadImage()        Sets the current record's "head_image" value
 * @method Layout              setBackgroundImage()  Sets the current record's "background_image" value
 * @method Layout              setBottomImage()      Sets the current record's "bottom_image" value
 * @method Layout              setPoll()             Sets the current record's "Poll" collection
 * 
 * @package    ibum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLayout extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('layout');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('head_image', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('background_image', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('bottom_image', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Poll', array(
             'local' => 'id',
             'foreign' => 'layout_id'));
    }
}