<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UsersExplains', 'doctrine');

/**
 * BaseUsersExplains
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $user_id
 * @property string $answer_text
 * @property timestamp $created_at
 * @property Users $Users
 * 
 * @method string        getUserId()      Returns the current record's "user_id" value
 * @method string        getAnswerText()  Returns the current record's "answer_text" value
 * @method timestamp     getCreatedAt()   Returns the current record's "created_at" value
 * @method Users         getUsers()       Returns the current record's "Users" value
 * @method UsersExplains setUserId()      Sets the current record's "user_id" value
 * @method UsersExplains setAnswerText()  Sets the current record's "answer_text" value
 * @method UsersExplains setCreatedAt()   Sets the current record's "created_at" value
 * @method UsersExplains setUsers()       Sets the current record's "Users" value
 * 
 * @package    ibum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsersExplains extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('users_explains');
        $this->hasColumn('user_id', 'string', 70, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 70,
             ));
        $this->hasColumn('answer_text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Users', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}