<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Logs', 'doctrine');

/**
 * BaseLogs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $user_id
 * @property string $type
 * @property string $message
 * @property string $details
 * @property timestamp $created_at
 * 
 * @method integer   getId()         Returns the current record's "id" value
 * @method string    getUserId()     Returns the current record's "user_id" value
 * @method string    getType()       Returns the current record's "type" value
 * @method string    getMessage()    Returns the current record's "message" value
 * @method string    getDetails()    Returns the current record's "details" value
 * @method timestamp getCreatedAt()  Returns the current record's "created_at" value
 * @method Logs      setId()         Sets the current record's "id" value
 * @method Logs      setUserId()     Sets the current record's "user_id" value
 * @method Logs      setType()       Sets the current record's "type" value
 * @method Logs      setMessage()    Sets the current record's "message" value
 * @method Logs      setDetails()    Sets the current record's "details" value
 * @method Logs      setCreatedAt()  Sets the current record's "created_at" value
 * 
 * @package    ibum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLogs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('logs');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'string', 70, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 70,
             ));
        $this->hasColumn('type', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('message', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('details', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}