<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AnswersStat', 'doctrine');

/**
 * BaseAnswersStat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $answer_id
 * @property float $votes
 * @property timestamp $created_at
 * @property QuestionsAnswers $QuestionsAnswers
 * 
 * @method integer          getId()               Returns the current record's "id" value
 * @method integer          getAnswerId()         Returns the current record's "answer_id" value
 * @method float            getVotes()            Returns the current record's "votes" value
 * @method timestamp        getCreatedAt()        Returns the current record's "created_at" value
 * @method QuestionsAnswers getQuestionsAnswers() Returns the current record's "QuestionsAnswers" value
 * @method AnswersStat      setId()               Sets the current record's "id" value
 * @method AnswersStat      setAnswerId()         Sets the current record's "answer_id" value
 * @method AnswersStat      setVotes()            Sets the current record's "votes" value
 * @method AnswersStat      setCreatedAt()        Sets the current record's "created_at" value
 * @method AnswersStat      setQuestionsAnswers() Sets the current record's "QuestionsAnswers" value
 * 
 * @package    ibum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnswersStat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('answers_stat');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('answer_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('votes', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('QuestionsAnswers', array(
             'local' => 'answer_id',
             'foreign' => 'id'));
    }
}