<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BestAnswers', 'doctrine');

/**
 * BaseBestAnswers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $user_id
 * @property integer $question_id
 * @property string $answer_text
 * @property timestamp $created_at
 * @property Questions $Questions
 * @property Users $Users
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method string      getUserId()      Returns the current record's "user_id" value
 * @method integer     getQuestionId()  Returns the current record's "question_id" value
 * @method string      getAnswerText()  Returns the current record's "answer_text" value
 * @method timestamp   getCreatedAt()   Returns the current record's "created_at" value
 * @method Questions   getQuestions()   Returns the current record's "Questions" value
 * @method Users       getUsers()       Returns the current record's "Users" value
 * @method BestAnswers setId()          Sets the current record's "id" value
 * @method BestAnswers setUserId()      Sets the current record's "user_id" value
 * @method BestAnswers setQuestionId()  Sets the current record's "question_id" value
 * @method BestAnswers setAnswerText()  Sets the current record's "answer_text" value
 * @method BestAnswers setCreatedAt()   Sets the current record's "created_at" value
 * @method BestAnswers setQuestions()   Sets the current record's "Questions" value
 * @method BestAnswers setUsers()       Sets the current record's "Users" value
 * 
 * @package    ibum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBestAnswers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('best_answers');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'string', 70, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 70,
             ));
        $this->hasColumn('question_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('answer_text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Questions', array(
             'local' => 'question_id',
             'foreign' => 'id'));

        $this->hasOne('Users', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}