<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DemographicStat', 'doctrine');

/**
 * BaseDemographicStat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $user_id
 * @property string $city
 * @property string $sex
 * @property integer $age
 * @property timestamp $created_at
 * @property Users $Users
 * 
 * @method integer         getId()         Returns the current record's "id" value
 * @method string          getUserId()     Returns the current record's "user_id" value
 * @method string          getCity()       Returns the current record's "city" value
 * @method string          getSex()        Returns the current record's "sex" value
 * @method integer         getAge()        Returns the current record's "age" value
 * @method timestamp       getCreatedAt()  Returns the current record's "created_at" value
 * @method Users           getUsers()      Returns the current record's "Users" value
 * @method DemographicStat setId()         Sets the current record's "id" value
 * @method DemographicStat setUserId()     Sets the current record's "user_id" value
 * @method DemographicStat setCity()       Sets the current record's "city" value
 * @method DemographicStat setSex()        Sets the current record's "sex" value
 * @method DemographicStat setAge()        Sets the current record's "age" value
 * @method DemographicStat setCreatedAt()  Sets the current record's "created_at" value
 * @method DemographicStat setUsers()      Sets the current record's "Users" value
 * 
 * @package    ibum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDemographicStat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('demographic_stat');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'string', 70, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 70,
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('sex', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('age', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Users', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}