<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/02/12 09:13:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=58629.m.tld.pl;dbname=baza58629_cudm',
  'username' => 'admin58629_cudm',
  'password' => 'q4k3gH2P',
  'name' => 'doctrine',
)),);
