<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/12 09:13:12
sfConfig::add(array(
  'app_facebook_app_id' => '188461161172960',
  'app_facebook_secret_key' => '6e5213eefaa51b0e97fa30f14fddefe5',
  'app_facebook_api_key' => '87c803cbc7b13e4c3eea8ea79d98d0df',
  'app_facebook_permissions' => 'publish_stream',
  'app_facebook_funpage_id' => '121401087931949',
  'app_frontend_url' => 'http://apps.facebook.com/cudmalinaradzi/',
  'app_server_url' => 'http://cudmalina.filesbook.pl/',
  'app_allow_publish' => 1,
));
