<?php

/**
 * AnswersStatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnswersStatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnswersStatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnswersStat');
    }
}