<?php

/**
 * BestAnswersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BestAnswersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BestAnswersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BestAnswers');
    }
}