<?php

/**
 * DemographicStatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DemographicStatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DemographicStatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DemographicStat');
    }
}