<?php

/**
 * LayoutTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LayoutTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LayoutTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Layout');
    }
}