<?php

/**
 * LogsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Logs');
    }
}