<?php

/**
 * PollCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PollCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PollCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PollComment');
    }
}