<?php

/**
 * QuestionsAnswersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuestionsAnswersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuestionsAnswersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuestionsAnswers');
    }
}