<?php

/**
 * QuestionsResultsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuestionsResultsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuestionsResultsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuestionsResults');
    }
}