<?php

/**
 * UsersExplainsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsersExplainsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsersExplainsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsersExplains');
    }
}