<?php

/**
 * UsersAnswersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsersAnswersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsersAnswersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsersAnswers');
    }
}