<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/10 16:05:32

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=u_poll',
  'username' => 'u_poll',
  'password' => 'tgbu_poll12#',
  'name' => 'doctrine',
)),);
