<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/05/10 13:55:38
sfConfig::add(array(
  'app_facebook_app_id' => '195365697172204',
  'app_facebook_secret_key' => 'ccf61b3ded71bf895879e7eda14ff5d7',
  'app_facebook_api_key' => 'ad1e2c44c30808c5220001826c19aa9c',
  'app_facebook_permissions' => 'publish_stream',
  'app_facebook_funpage_id' => '150814674957466',
  'app_frontend_url' => 'http://apps.facebook.com/geek_pc/',
  'app_server_url' => 'http://poll.dev/',
  'app_allow_publish' => 1,
));
