<?php
// auto-generated by sfViewConfigHandler
// date: 2011/05/10 21:42:51
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('screen.css?v=2', '', array ());
  $response->addStylesheet('main.css?v=1305056571', '', array ());
  $response->addJavascript('http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.5.1.js', '', array ());
  $response->addJavascript('http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.10/jquery-ui.js', '', array ());
  $response->addJavascript('cookie.js', '', array ());
  $response->addJavascript('frontend.js?v=1305056571', '', array ());
  $response->addJavascript('jquery.imagetick.js', '', array ());


