<?php
// auto-generated by sfViewConfigHandler
// date: 2011/01/29 23:47:44
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('screen.css?v=2', '', array ());
  $response->addStylesheet('main.css?v=1296341264', '', array ());
  $response->addJavascript('https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js', '', array ());
  $response->addJavascript('https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/jquery-ui.min.js', '', array ());
  $response->addJavascript('https://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js', '', array ());
  $response->addJavascript('cookie.js', '', array ());
  $response->addJavascript('frontend.js?v=1296341264', '', array ());
  $response->addJavascript('jquery.imagetick.js', '', array ());


